### PR TITLE
Increase max arrays to 1800

### PR DESCRIPTION
**Pull request by pllim**
🤷‍♀

### CODE REVIEW

**Review by mcara — APPROVED** [review]
LGTM

**Review by hbushouse — APPROVED** [review]
This value will (just barely) fix the one problem case we've run into so far. I think it might be worth allowing for a bit of headroom and hence maybe bump this up a little more to, say, 1800?

**Comment by pllim** [comment]
Bumped.

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
Is it OK to merge this?

**Comment by pllim** [comment]
`#yolo`

**Pull request merged**
