### PR TITLE
Remove nose test dependency

### LINKED ISSUE #7: NPY C deprecations
Seeing the following running under py3.7 and npy 1.15.2:
```
/Users/jdavies/anaconda3/envs/jwst_dev/lib/python3.7/site-packages/stsci.image-2.3.0-py3.7-macosx-10.7-x86_64.egg/stsci/image/combine.py:22: DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
  _combine(arrays, out, nlow, nhigh, badmasks, funcstr)
/Users/jdavies/anaconda3/envs/jwst_dev/lib/python3.7/site-packages/stsci.image-2.3.0-py3.7-macosx-10.7-x86_64.egg/stsci/image/combine.py:22: DeprecationWarning: UPDATEIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing
  _combine(arrays, out, nlow, nhigh, badmasks, funcstr)
```

### PR DESCRIPTION
**Pull request by jdavies-st**
- Remove `nose` dependency in tests.  Now just use `pytest` at the top level
- Fix Numpy deprecation warnings.

Resolves #7.

### CODE REVIEW

**Comment by jdavies-st** [comment]
It would be nice to get TravisCI or any other CI on this repo.  Running locally, commits above pass, the 2nd without the deprecation warnings.  Just using `pytest`.

**Comment by nden** [comment]
We decided we'll try moving this upstream.  There was agreement to make sure tests run locally but no  need to hook a CI system.

**Comment by jdavies-st** [comment]
OK, that makes sense.  At least this fixes up the tests.  I needed those to make sure I wasn't breaking things with fixing the DeprecationWarnings.

That said, I'm not positive I've done that correctly.  Then again, no warnings now, and the tests all pass as before.

**Comment by jdavies-st** [comment]
I don't think these doctests have been run anytime since the release of `numpy 1.13`.   They too now pass.  I removed the examples in the deprecated `NumCombine` class.  That way we don't get `DeprecationWarnings` when running the tests.

**Pull request merged**
