### PR TITLE
Convert to setuptools and setuptools_scm for versioning

### PR DESCRIPTION
**Pull request by jdavies-st**
In a fresh conda env:
```
$ git clean -xdf
$ pip install numpy pytest
$ python setup.py sdist
running sdist
running egg_info
creating stsci.image.egg-info
writing stsci.image.egg-info/PKG-INFO
writing dependency_links to stsci.image.egg-info/dependency_links.txt
writing requirements to stsci.image.egg-info/requires.txt
writing top-level names to stsci.image.egg-info/top_level.txt
writing manifest file 'stsci.image.egg-info/SOURCES.txt'
writing manifest file 'stsci.image.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating stsci.image-2.3.3.dev4+g359d87c
creating stsci.image-2.3.3.dev4+g359d87c/docs
creating stsci.image-2.3.3.dev4+g359d87c/docs/source
creating stsci.image-2.3.3.dev4+g359d87c/src
creating stsci.image-2.3.3.dev4+g359d87c/stsci
creating stsci.image-2.3.3.dev4+g359d87c/stsci.image.egg-info
creating stsci.image-2.3.3.dev4+g359d87c/stsci/image
creating stsci.image-2.3.3.dev4+g359d87c/stsci/image/test
copying files to stsci.image-2.3.3.dev4+g359d87c...
copying .gitignore -> stsci.image-2.3.3.dev4+g359d87c
copying LICENSE.txt -> stsci.image-2.3.3.dev4+g359d87c
copying pyproject.toml -> stsci.image-2.3.3.dev4+g359d87c
copying setup.py -> stsci.image-2.3.3.dev4+g359d87c
copying docs/Makefile -> stsci.image-2.3.3.dev4+g359d87c/docs
copying docs/make.bat -> stsci.image-2.3.3.dev4+g359d87c/docs
copying docs/source/conf.py -> stsci.image-2.3.3.dev4+g359d87c/docs/source
copying docs/source/image.rst -> stsci.image-2.3.3.dev4+g359d87c/docs/source
copying docs/source/index.rst -> stsci.image-2.3.3.dev4+g359d87c/docs/source
copying docs/source/numcombine.rst -> stsci.image-2.3.3.dev4+g359d87c/docs/source
copying src/_combinemodule.c -> stsci.image-2.3.3.dev4+g359d87c/src
copying stsci/__init__.py -> stsci.image-2.3.3.dev4+g359d87c/stsci
copying stsci.image.egg-info/PKG-INFO -> stsci.image-2.3.3.dev4+g359d87c/stsci.image.egg-info
copying stsci.image.egg-info/SOURCES.txt -> stsci.image-2.3.3.dev4+g359d87c/stsci.image.egg-info
copying stsci.image.egg-info/dependency_links.txt -> stsci.image-2.3.3.dev4+g359d87c/stsci.image.egg-info
copying stsci.image.egg-info/requires.txt -> stsci.image-2.3.3.dev4+g359d87c/stsci.image.egg-info
copying stsci.image.egg-info/top_level.txt -> stsci.image-2.3.3.dev4+g359d87c/stsci.image.egg-info
copying stsci/image/__init__.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image
copying stsci/image/_image.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image
copying stsci/image/combine.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image
copying stsci/image/numcombine.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image
copying stsci/image/test/__init__.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image/test
copying stsci/image/test/test_average.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image/test
copying stsci/image/test/test_median.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image/test
copying stsci/image/test/test_minimum.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image/test
copying stsci/image/test/test_threshold.py -> stsci.image-2.3.3.dev4+g359d87c/stsci/image/test
Writing stsci.image-2.3.3.dev4+g359d87c/setup.cfg
creating dist
Creating tar archive
removing 'stsci.image-2.3.3.dev4+g359d87c' (and everything under it)
```

```
$ pip install dist/stsci.image-2.3.3.dev4+g359d87c.tar.gz 
Processing ./dist/stsci.image-2.3.3.dev4+g359d87c.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy (from stsci.image==2.3.3.dev4+g359d87c)
  Using cached https://files.pythonhosted.org/packages/04/66/ec5f1283d6a290a9153881a896837487338c44639c1305cc59e1c7b69cc9/scipy-1.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: numpy>=1.13 in /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages (from stsci.image==2.3.3.dev4+g359d87c) (1.16.4)
Building wheels for collected packages: stsci.image
  Building wheel for stsci.image (PEP 517) ... done
  Stored in directory: /Users/jdavies/Library/Caches/pip/wheels/98/67/b0/3418306c222745c0804cc3d4ee95c88a43ecaaacfb887d8cf3
Successfully built stsci.image
Installing collected packages: scipy, stsci.image
Successfully installed scipy-1.3.0 stsci.image-2.3.3.dev4+g359d87c
```

```
$ pytest --pyargs stsci.image --doctest-plus
=========================== test session starts ============================
platform darwin -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /Users/jdavies/dev/stsci.image
plugins: doctestplus-0.3.0
collected 29 items                                                         

combine.py ......                                                    [ 20%]
numcombine.py .                                                      [ 24%]
test/test_average.py ......                                          [ 44%]
test/test_median.py ......                                           [ 65%]
test/test_minimum.py ......                                          [ 86%]
test/test_threshold.py ....                                          [100%]

======================== 29 passed in 0.39 seconds =========================
```
Closes #2

### CODE REVIEW

**Comment by jdavies-st** [comment]
After the above, we can also do a dev install and test
```
$ pip install -e .
Obtaining file:///Users/jdavies/dev/stsci.image
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13 in /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages (from stsci.image==2.3.3.dev4+g359d87c) (1.16.4)
Requirement already satisfied: scipy in /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages (from stsci.image==2.3.3.dev4+g359d87c) (1.3.0)
Installing collected packages: stsci.image
  Found existing installation: stsci.image 2.3.3.dev4+g359d87c
    Uninstalling stsci.image-2.3.3.dev4+g359d87c:
      Successfully uninstalled stsci.image-2.3.3.dev4+g359d87c
  Running setup.py develop for stsci.image
Successfully installed stsci.image

$ pytest --doctest-plus
============================ test session starts ============================
platform darwin -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /Users/jdavies/dev/stsci.image
plugins: doctestplus-0.3.0
collected 29 items                                                          

stsci/image/combine.py ......                                         [ 20%]
stsci/image/numcombine.py .                                           [ 24%]
stsci/image/test/test_average.py ......                               [ 44%]
stsci/image/test/test_median.py ......                                [ 65%]
stsci/image/test/test_minimum.py ......                               [ 86%]
stsci/image/test/test_threshold.py ....                               [100%]

========================= 29 passed in 0.58 seconds =========================
```

**Comment by jdavies-st** [comment]
Correction.  We can do a straight dev install.  In a fresh conda env:
```
$ pip install numpy pytest pytest-doctestplus
$ git clean -xdf
$ python setup.py develop
running develop
running egg_info
creating stsci.image.egg-info
writing stsci.image.egg-info/PKG-INFO
writing dependency_links to stsci.image.egg-info/dependency_links.txt
writing requirements to stsci.image.egg-info/requires.txt
writing top-level names to stsci.image.egg-info/top_level.txt
writing manifest file 'stsci.image.egg-info/SOURCES.txt'
writing manifest file 'stsci.image.egg-info/SOURCES.txt'
running build_ext
building 'stsci.image._combine' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.7
creating build/temp.macosx-10.7-x86_64-3.7/src
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jdavies/miniconda3/envs/test/include -arch x86_64 -I/Users/jdavies/miniconda3/envs/test/include -arch x86_64 -DNUMPY=1 -I/Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/core/include -I/Users/jdavies/miniconda3/envs/test/include/python3.7m -c src/_combinemodule.c -o build/temp.macosx-10.7-x86_64-3.7/src/_combinemodule.o
In file included from src/_combinemodule.c:2:
In file included from /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
/Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
src/_combinemodule.c:268:20: warning: comparison of integers of different
      signs: 'int' and 'unsigned long' [-Wsign-compare]
    for (i=0,f=0; i<(sizeof(functions)/sizeof(functions[0])); i++)
                  ~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/_combinemodule.c:78:1: warning: unused function '_inner_old_median'
      [-Wunused-function]
_inner_old_median(int goodpix, int nlow, int nhigh, int ninputs,
^
3 warnings generated.
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/stsci
creating build/lib.macosx-10.7-x86_64-3.7/stsci/image
gcc -bundle -undefined dynamic_lookup -L/Users/jdavies/miniconda3/envs/test/lib -arch x86_64 -L/Users/jdavies/miniconda3/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/src/_combinemodule.o -o build/lib.macosx-10.7-x86_64-3.7/stsci/image/_combine.cpython-37m-darwin.so
copying build/lib.macosx-10.7-x86_64-3.7/stsci/image/_combine.cpython-37m-darwin.so -> stsci/image
Creating /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/stsci.image.egg-link (link to .)
Adding stsci.image 2.3.3.dev4+g359d87c to easy-install.pth file

Installed /Users/jdavies/dev/stsci.image
Processing dependencies for stsci.image==2.3.3.dev4+g359d87c
Searching for scipy
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/04/66/ec5f1283d6a290a9153881a896837487338c44639c1305cc59e1c7b69cc9/scipy-1.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=09d008237baabf52a5d4f5a6fcf9b3c03408f3f61a69c404472a16861a73917e
Best match: scipy 1.3.0
Processing scipy-1.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing scipy-1.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl to /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages
writing requirements to /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/scipy-1.3.0-py3.7-macosx-10.7-x86_64.egg/EGG-INFO/requires.txt
Adding scipy 1.3.0 to easy-install.pth file

Installed /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages/scipy-1.3.0-py3.7-macosx-10.7-x86_64.egg
Searching for numpy==1.16.4
Best match: numpy 1.16.4
Adding numpy 1.16.4 to easy-install.pth file
Installing f2py script to /Users/jdavies/miniconda3/envs/test/bin
Installing f2py3 script to /Users/jdavies/miniconda3/envs/test/bin
Installing f2py3.7 script to /Users/jdavies/miniconda3/envs/test/bin

Using /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages
Finished processing dependencies for stsci.image==2.3.3.dev4+g359d87c
```
And the tests pass.
```
$ pytest --doctest-plus
============================ test session starts ============================
platform darwin -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /Users/jdavies/dev/stsci.image
plugins: doctestplus-0.3.0
collected 29 items                                                          

stsci/image/combine.py ......                                         [ 20%]
stsci/image/numcombine.py .                                           [ 24%]
stsci/image/test/test_average.py ......                               [ 44%]
stsci/image/test/test_median.py ......                                [ 65%]
stsci/image/test/test_minimum.py ......                               [ 86%]
stsci/image/test/test_threshold.py ....                               [100%]

========================= 29 passed in 0.66 seconds =========================

```

**Comment by jdavies-st** [comment]
And `pip install -e` works fine in a fresh conda env too:
```
$ pip install numpy pytest pytest-doctestplus
$ git clean -xdf
$ pip install -e .
Obtaining file:///Users/jdavies/dev/stsci.image
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13 in /Users/jdavies/miniconda3/envs/test/lib/python3.7/site-packages (from stsci.image==2.3.3.dev4+g359d87c) (1.16.4)
Collecting scipy (from stsci.image==2.3.3.dev4+g359d87c)
  Using cached https://files.pythonhosted.org/packages/04/66/ec5f1283d6a290a9153881a896837487338c44639c1305cc59e1c7b69cc9/scipy-1.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: scipy, stsci.image
  Running setup.py develop for stsci.image
Successfully installed scipy-1.3.0 stsci.image

$ pytest --doctest-plus
============================ test session starts ============================
platform darwin -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /Users/jdavies/dev/stsci.image
plugins: doctestplus-0.3.0
collected 29 items                                                          

stsci/image/combine.py ......                                         [ 20%]
stsci/image/numcombine.py .                                           [ 24%]
stsci/image/test/test_average.py ......                               [ 44%]
stsci/image/test/test_median.py ......                                [ 65%]
stsci/image/test/test_minimum.py ......                               [ 86%]
stsci/image/test/test_threshold.py ....                               [100%]

========================= 29 passed in 0.49 seconds =========================
```

**Review by jhunkeler — APPROVED** [review]
Looks good to me! :santa: :rocket:

Edit: Nice job

**Pull request merged**
